name: kitapapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  flutter_redux: ^0.9.0
  redux: ^5.0.0-nullsafety
  mockito: ^5.0.1
  copy_with_extension: ^4.0.0
  workmanager: ^0.5.1
  very_good_analysis: ^5.1.0 
  

  flutter_localizations:
    sdk: flutter
  easy_splash_screen: ^1.0.4
  persistent_bottom_nav_bar: ^6.2.1
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.4
  copy_with_extension_gen: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/stephen.png
   
